### ISSUE TITLE
Pepper

### ISSUE THREAD

**Issue by lostinblue** [rubyclerks/office_clerk#6]
I don't know if that is your production pepper but you accidentally left it inline in the model. You may want to move that to a config file. 

Take care.

**Comment by dancinglightning** [comment]
Hi lostinblue

You may want to make a little more introduction on a post :-)
And possibly make the description better, and essentially, read the code to know that you have a point.

Otherwise, like in this case, your "help" comes across as a knee jerk criticism.

It does seem like i forgot a PEPPER variable lying around, but it is not used. Which you would know if you read the code.

Take a breather and ask yourself if this really was you being helpful, as you probably thought at the time.
